[mcp_servers.linkedin-social-research]
command = "uv"
args = ["run", "./.agents/linkedin-social-writer/mcp/social-research/server.py"]

[mcp_servers.blog-image-finder]
command = "uv"
args = ["run", "./.agents/blog-image-finder/mcp/image-provider/server.py"]

[mcp_servers.blog-image-uploader]
command = "uv"
args = ["run", "./.agents/blog-image-uploader/mcp/blog-image-s3/server.py"]
